name: Deploy to VPS
on: 
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Kodni yuklash
              uses: actions/chekout@v4

            - name: SSH kalitni sozlash
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
              shell: bash
            - name: Serverga deploy qilish
              env: 
                HOST: ${{ secrets.HOST }}
                USER: ${{ secrets.USERNAME }}
                APP_DIR: /ci_Cd
                PORT: ${{ secrets.PORT}}
            run: |
                ssh-keysan -H $HOST >> ~/.ssh/known_host
                ssh $USER@HOST "
                    if [ ! -d $APP_DIR ]; then
                        mkdir -p $APP_DIR
                        git clone https://github.com/repowpolsturk/CI-CD-Actions $APP_DIR 
                        cd $APP_DIR
                        echo 'POSRT"=${PORT}'' > .env
                    else
                      cd $APP_DIR
                      git pull origin main
                    fi
                    npm install 
                    npm run build 
                    pm2 restart ci_cd_app || pm2 start dist/main.js --name ci_cd_app
                "
            shell: bash